export const gamestate = {
  uid: "",
  points: 0,
  planet: "nono",
  buildings: [
    "non0.no0.no0.no0.no0",
    "non0.no0.no0.no0.no0",
    "non0.no0.no0.no0.no0",
    "non0.no0.no0.no0.no0",
    "non0.no0.no0.no0.no0",
    "non0.no0.no0.no0.no0",
    "non0.no0.no0.no0.no0",
    "non0.no0.no0.no0.no0",
  ],
  sky: ["non", "non", "non", "non", "non", "non", "non", "non"],
  goodStartBoost: 0,
  extensiveBoost: 0,
  activeBoost: false,
  planetPosition: 1,
  trackingData: {
    testGroup: "",
    planetClicks: 0,
    bannerInteractions: 0,
    editTreeClicks: 0,
    turnClicks: 0,
    boosts: 0,
    suggestionClicks: 0,
    boostKind: {
      goodStartAmount: 0,
      extensiveAmount: 0,
    },
    // pointsPerSlide: [],
    wordsWritten: 0,
    email: "beispiel@email.com",
    contactQuery: false,
    triggeredPoints: "",
  },
};
